[package]
name = "egomoose/rich-text-helper"
description = "https://github.com/EgoMoose/rich-text-helper"
version = "0.2.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
exclude = ["**"]
include = ["src", "src/**", "wally.toml", "wally.lock", "default.project.json", "LICENSE"]

[dependencies]
Sift = "csqrl/sift@0.0.9"

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"